### ISSUE TITLE
Alpha ESS Website

### ISSUE THREAD

**Issue by strickersuk** [DasLetzteEinhorn/AlphaESS_Monitor_Hass#9]
Website changed to cloud.alphaess.com, seems to have broken the add on?

**Comment by DasLetzteEinhorn** [comment]
Yup, I'll see when I find some time to fix it. Already noticed a few days ago, that the website uses a different API Endpoint to fetch the data.

**Comment by strickersuk** [comment]
DNS rewrite using AdGuard from www.alphaess.com to cloud.alphaess.com seems to be working as a temp fix. I’ll monitor and post back if it stops working.

**Comment by Spookster** [comment]
> DNS rewrite using AdGuard from [www.alphaess.com](http://www.alphaess.com) to cloud.alphaess.com seems to be working as a temp fix. I’ll monitor and post back if it stops working.

Can you expand on your temp fix and what you did? Its leaving us high and dry at the moment with no automatons triggered

**Comment by strickersuk** [comment]
I’m running AdGuard as an add-on, it allows me to DNS rewrite internet URLs to local IPs. For example, www.ha.com to 192.168.1.5, so I don’t have to route HA activity over the internet as it’s attached to a real website. I just added an additional DNS rewrite from www.alphaess.com to cloud.alphaess.com. I have notice in the last few hours that things have stopped working but so has the AlphaESS App so I assume that’s related to the changes.

**Comment by strickersuk** [comment]
Just to add that any request for www.alphaess.com will be replaced with cloud.alphaess.com on my local network. Doesn’t matter what makes the request apart from anything Apple of course with private relay enabled.

**Comment by Spookster** [comment]
Where in the settings are you doing it? (fresh adguard user)
![image](https://user-images.githubusercontent.com/982535/176779271-227b647f-b245-463d-8a53-ac5aaf6bbc82.png)

**Comment by strickersuk** [comment]
I think it's all a bit academic right now, I'm getting no data from cloud.alphaess.com?

**Comment by strickersuk** [comment]
<img width="595" alt="Screenshot 2022-07-01 at 05 39 55" src="https://user-images.githubusercontent.com/105049426/176824603-af181896-dd81-4ebe-a5ad-bc43370e1848.png">

I'm getting this from the dongle whether I have the DNS rewrite in place or not?

Also, looking at what you have above this looks like a browser extension not the full-fledged HA add-on which replaces your DNS.

**Comment by strickersuk** [comment]
Can't say it won't fall over again and as I said this is a temp fix. I have now created custom client settings for the AlphaESS dongle and added the DNS rewrite for other clients.

<img width="632" alt="Screenshot 2022-07-01 at 07 14 27" src="https://user-images.githubusercontent.com/105049426/176835416-740d8beb-ff07-4c9e-8022-92bef4d31ea5.png">
<img width="1127" alt="Screenshot 2022-07-01 at 07 14 39" src="https://user-images.githubusercontent.com/105049426/176835475-ce0ac69f-d2c6-4b63-8096-1b05d71ce3f1.png">

**Comment by nmthas** [comment]
@Spookster from the menu in your picture select "Filters" and then "DNS rewrites" then you can add a DNS rewrite for www.alphaess.com to cloud.alphaess.com

![image](https://user-images.githubusercontent.com/39108642/176837472-c3377d5e-a61f-45b5-b0c4-0dd0346e6225.png)

**Comment by strickersuk** [comment]
Yeah, its working for me but it seemed to block the battery with communicating directly with just the rewrite. That's why I set the battery as a custom client and pointed it at Google's DNS server. Seems to be working for now, hopefully a quick fix when DasLetzeEinhorn finds some time.

**Comment by DasLetzteEinhorn** [comment]
hey guys,

currently working on a fix. even though i pushed a new version to the master branch, please DON'T update yet. Doesn't work as of now. Will post an update here as soon as it works :)

**Comment by DasLetzteEinhorn** [comment]
should work now, could you please test the version 0.1.4 and let me know if it works on your system as well?
thanks!

**Comment by Spookster** [comment]
Working here, thanks!

**Comment by strickersuk** [comment]
Seems good, many thanks.

**Comment by nmthas** [comment]
> should work now, could you please test the version 0.1.4 and let me know if it works on your system as well? thanks!

Thanks all good for me too with 0.1.4
